# -*- coding: utf-8 -*-
PROD_MONGODB_SERVER = ""
PROD_MONGODB_PORT = ""
PROD_MONGODB_USERNAME = ""
PROD_MONGODB_PASSWORD = ""
PROD_MONGODB_DBNAME = ""
PROD_SERVER = ""
PROD_SERVER_SSH_PORT = ""
PROD_SERVER_SSH_USERNAME = ""
PROD_SERVER_SSH_PASSWORD = ""
SYNC_EXCLUDE_COLLECTIONS = []
FILE_LIST = []
LOCAL_MONGODB_ADDRESS = ""
LOCAL_MONGODB_PORT = ""
